### ISSUE TITLE
Issues with server side rendering.

### ISSUE THREAD

**Issue by ghost** [ZitRos/react-xmasonry#10]
Hey there,
We're trying this with this starter kit https://github.com/kriasoft/react-starter-kit. The issue that we're having is that we get an empty div when the client renders. If we disable Javascript, we get all the `<XBlock>` items. With Javascript enabled we see the first load on the server and then all content disappears.
We wrapped the content in a div (display block) as you suggest in #2 
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div class="xmasonry" style="position:re
 (server) <div class="xmasonry xmasonry-static" st
```

Any ideas what could be the issue?

Thanks!

**Comment by nikitaeverywhere** [comment]
Interesting. Thank you Alejandro again for pointing on XMasonry issues.

I see the problem. I think it's a major server-side rendering algorithm cons. When designing it, I was expecting that server-side rendered markup will never go directly to browser but to search bots for example.

Could you please create a demonstation code/repo for this problem? It would dramatically save my time and I suppose you already have a setup.

Thank you!

P.S. Expect me to get back to this in ~17 hours, hopefully that's okay to you!

**Comment by alejandronanez** [comment]
Hey @zitros thanks a lot for your collaboration!
I have the code on a private repo but let me see if I can repro it locally with a new project.

Thanks again!

**Comment by alejandronanez** [comment]
Hey @ZitRos I couldn't replicate this locally. Here's the repo (the warning is still there though)
https://github.com/alejandronanez/ssr-masonry

Any clue you have about how we can make this work is really appreciated!

Thanks!

**Comment by nikitaeverywhere** [comment]
Aha, it's just a warning. The reason behind this is that XMasonry adds some additional stylings while rendering on the server.

I think we can simply remove those styles as they can be defined another way, by the user. But before doing this, please, check whether [this helps](https://stackoverflow.com/questions/33521047/warning-react-attempted-to-reuse-markup-in-a-container-but-the-checksum-was-inv). Thank you!

**Comment by ghost** [comment]
Sweet! We really like this module, thanks a lot for building it.

We can close this issue then.

**Comment by nikitaeverywhere** [comment]
Thank you for the feedback!

Did the SO answers I linked eliminated the warning? I wasn't diving deep to React's server side rendering so it may be a good topic to discuss. Anyway, tell me if it's on XMasonry side.

Cheers!

**Comment by ghost** [comment]
We haven't tried that yet! Will let you know once we try it though.

**Comment by nikitaeverywhere** [comment]
I'm just trying to figure out why have you closed the issue if the warning
message was not eliminated :)

**Comment by paustria** [comment]
I'm having this issue. How do we fix this?

**Comment by nikitaeverywhere** [comment]
@paustria, could you please post a simple reproduction/demo of the issue? It would be much appreciated.
