### ISSUE TITLE
Having a bit of an issue

### ISSUE THREAD

**Issue by jimmycarlinco** [ZitRos/react-xmasonry#17]
I am using this library to display a grid of data elements. Everything works perfectly when the grid is displayed statically. However my application is real time and new data elements are pushed from socket periodically. In addition there is infinite scroll so when user scrolls down 20 new data elements are loaded. 

Now the xmasonry grid will glitch when the following sequence of actions happens:
user scrollls down and triggers loading 20 new elements > before the load finishes 1 new real time item is added > load of 20 new elements finishes.
This will cause the grid to render multiple children with the same key.

Seems like if the grid is still readjusting itself after the props  change, it will somehow break.

This is driving me insane and maybe you can point me in the right direction? What do you think is the reason for the issue? A thousand thanks if you can help me.

**Comment by nikitaeverywhere** [comment]
Hello!

Thank you for reaching out.

From what I've tested, if you add elements sequentially (and even if randomly) it should never be an issue as far as you specify `key="whatever"` attribute for `XBlock`. Are you sure it is not your code which assigns duplicated keys to `XBlock`s? If not, I would love to see the [codepen](https://codepen.io/ZitRos/pen/GmrLQB) which reproduces the issue so I can clearly see what's wrong. There's definitely a lot of magic happening for [assigned keys](https://github.com/ZitRos/react-xmasonry/blob/master/src/components/XMasonry.jsx#L377).

**Comment by jimmycarlinco** [comment]
You are right, your library is flawless! :D It was my own faulty reducer. Closing

**Comment by nikitaeverywhere** [comment]
Thanks! :) Good luck!
