### ISSUE TITLE
React v16.12.0: deprecated lifecycles

### ISSUE THREAD

**Issue by jellysquider** [ZitRos/react-xmasonry#18]
When using XMasonry I receive the following warnings about componentWillMount and componentWillReceiveProps:
![warnings](https://user-images.githubusercontent.com/16536278/75086956-243b3b80-54ef-11ea-81df-c8a44f0ead38.PNG)

Is there a plan to fix them in the future?

Thank you so much for making this!

**Comment by nikitaeverywhere** [comment]
Hello @jellysquider! Thank you for letting me know for this update in React.

Luckily [I was able to fix this](https://github.com/ZitRos/react-xmasonry/commit/a0078074eaa8cd8accf83222ba7d776561716b21) by refactoring things without breaking changes. `v3.0.2` should now vanish these warnings.

Please let me know if it does! Thank you!

**Comment by nikitaeverywhere** [comment]
Oops I see server-side rendering is affected

**Comment by nikitaeverywhere** [comment]
Fixed by 8ef73646ed2feb7959291086c8cad71376327629.

**Comment by jellysquider** [comment]
Great, thank you so much!
