### ISSUE TITLE
Does this work on IE11?

### ISSUE THREAD

**Issue by ghost** [ZitRos/react-xmasonry#8]
I'm trying to make this work in IE11 but I'm seeing this message `Loading...
 If you see this text, that means that your browser doesn't support latest React JS or you have network problems. Try refreshing the page or updating your browser. ` in my browser. Is there any workaround for this?

Thanks!

**Comment by nikitaeverywhere** [comment]
Hi, Alejandro!

Looks like it's about undefined `Array.from` in IE11. Thanks for reporting, I'll look at this shortly.

**Comment by nikitaeverywhere** [comment]
Alejandro, adding Array.from polyfill directly to `react-xmasonry` results in +2kb weight.

Will it be okay for you to use the polyfill out of the box?

**Comment by nikitaeverywhere** [comment]
The fix is published as `2.5.2`, thank you for noticing this! Please confirm that the issue is resolved.

**Comment by ghost** [comment]
Thanks, `2.5.2` fixed it. 👍
